# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_destination_trips'),
        ('login_reg_app', '0002_auto_20161118_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trips',
            field=models.ManyToManyField(to='app1.Destination'),
        ),
    ]
