# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
