# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0002_auto_20161118_1632'),
        ('app1', '0002_destination_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='going',
        ),
        migrations.AddField(
            model_name='destination',
            name='trips',
            field=models.ManyToManyField(to='login_reg_app.User'),
        ),
    ]
