# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20161118_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='trips',
        ),
    ]
