# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_destination_trips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='datefrom',
            field=models.DateField(max_length=40),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dateto',
            field=models.DateField(max_length=40),
        ),
    ]
