# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20161121_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='datefrom',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dateto',
            field=models.CharField(max_length=40),
        ),
    ]
